### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [openid/python-openid#102]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine openid/consumer/consumer.py, openid/test/test_ax.py, openid/test/test_consumer.py and observe `paramaters`, however expect to see `parameters`.
- Examine openid/consumer/consumer.py and observe `authenitcation`, however expect to see `authentication`.
- Examine openid/consumer/consumer.py and observe `respones`, however expect to see `response`.
- Examine openid/extensions/ax.py and observe `processsed`, however expect to see `processed`.
- Examine openid/consumer/consumer.py and observe `successfull`, however expect to see `successful`.
- Examine examples/djopenid/server/views.py and observe `intput`, however expect to see `input`.
- Examine openid/oidutil.py and observe `distict`, however expect to see `distinct`.
- Examine openid/yadis/xri.py and observe `comparsion`, however expect to see `comparison`.
- Examine openid/oidutil.py and observe `arguemtns`, however expect to see `arguments`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/python-openid/pull/new/bugfix_typos

Thanks.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
