### ISSUE TITLE
Serialize YadisServiceManager instance before writing it to session dict

### ISSUE THREAD

**Issue by jgehrcke** [openid/python-openid#17]
Here:

https://github.com/openid/python-openid/blob/12efd783e7b58aa72aff8feaff54bed1c133a3f9/openid/yadis/manager.py#L53

the whole `YadisServiceManager` instance gets written into the `session`, which is a dict-like object. This basically requires the web framework writing this session data somewhere (e.g. to a cookie) to use pickle as serializer, while sometimes JSON or others might be desired.

In my special case (Flask + OpenID-ext + itsdangerous-ext) this lead to: `<openid.yadis.manager.YadisServiceManager object at 0x9fa6f2c> is not JSON serializable` during the authentication process.

Therefore, it would be nice to have the serialization/deserialization done by python-openid, so that it is possible for python-openid to store a string to the session, which should not break any storage backend. By doing so, one could consider only storing the relevant data, because pickling this whole object for sure brings along some overhead.

Thanks for consideration,

Jan-Philip Gehrcke

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
