### ISSUE TITLE
Broken download link for python-openid==2.2.4 for Plone buildouts

### ISSUE THREAD

**Issue by jwhisnant** [openid/python-openid#2]
Getting required 'python-openid==2.2.4'
We have no distributions for python-openid that satisfies 'python-openid==2.2.4'.
Getting distribution for 'python-openid==2.2.4'.
While:
  Installing instance.
  Getting distribution for 'python-openid==2.2.4'.
Error: Can't download http://openidenabled.com/files/python-openid/packages/python-openid-2.2.4.tar.gz: 404 Not Found

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
