### ISSUE TITLE
ax.AXKeyValueMessage.getSingle will never raise KeyError

### ISSUE THREAD

**Issue by evgeni** [openid/python-openid#20]
https://github.com/openid/python-openid/blob/master/openid/extensions/ax.py#L546 says:
`@raises KeyError: If the attribute was not sent in this response`
However, KeyError is never raised explicitely and
`values = self.data.get(type_uri)` will return `None` when `type_uri` isn't found in `data`.

Either documentation or code should be edited :)

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
