### ISSUE TITLE
Example consumer works only if authentication response is GET method

### ISSUE THREAD

**Issue by jablko** [openid/python-openid#22]
The example consumer falls down if the OP sends an authentication response to the RP with POST method

In that case the example consumer reports 501 error: Unsupported method (POST)

This is because a ".do_POST()" isn't defined in examples/consumer.py

What happens is, you start the example consumer, enter an OpenID, send authentication request to OP, OP sends authentication response back to consumer. Authentication response is an indirect response - if the HTTP method is POST vs. GET, the consumer reports 501 error

I think the correct behavior is for the consumer to process the authentication response, like it processes the authentication response if the HTTP method is GET vs. POST. It should report that authentication succeeded or failed, like it does if the HTTP method is GET vs. POST

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
