### ISSUE TITLE
Can python-openid be used by desktop applications for authentication?

### ISSUE THREAD

**Issue by dequegorg** [openid/python-openid#30]
I've looked through the code you offer and it seemed it is designed for OpenID providers and consumers.
I am looking at a module that would help authenticating to an on-line service e.g. StackExchange, from a desktop application, without using an embedded browser.
I've worked on that myself, using Google Accounts as an OpenID provider, but doing this for all providers is quite some work. I don't want to duplicate existing work. Also, although my code is working, I'm not very literate with protocols on the Internet to be sure I'm doing the right thing.

In sum: is it possible to use python-openid for desktop applications to authenticate to provider and consumer?

Thanks.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
