### ISSUE TITLE
Missing import in openid.extension

### ISSUE THREAD

**Issue by kilink** [openid/python-openid#33]
This seemed too lightweight of an issue for a pull request, but the _toMessage_ method of _openid.extension.Extension_ references the _warnings_ module without it having been imported.

Test case:

``` Python
import openid.extension

ext = openid.extension.Extension()
ext.toMessage()
```

Even though this use of the method is deprecated, I consider it a bug.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
