### ISSUE TITLE
test_parsehtml.py now fails test runTest 

### ISSUE THREAD

**Issue by idella** [openid/python-openid#50]
python-yadis or python-openid   I really don't know which;   version   1.1.0.
python          version     Python 2.7.3
- Testing of dev-python/python-yadis-1.1.0-r1 with CPython 2.7...
  Checking code (pyflakes)... OK.
  Running tests... putting . in sys.path
  ..............................F.................................................
  ======================================================================
  FAIL: runTest (test_parsehtml._TestCase)
  24 (test_parsehtml<test1-parsehtml.txt>)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/python-yadis-1.1.0-r1/work/python-yadis-1.1.0/yadis/test/test_parsehtml.py", line 36, in runTest
    self.failUnless(self.expected == 'EOF', (self.case, self.expected))
  AssertionError: ('<!bad processing instruction!>\n', 'None')

---

Ran 80 tests in 0.036s

FAILED (failures=1)

My impression this is triggered by a change in python2.7 earlier this year.
Await your verdict.

distro gentoo..

**Comment by monsieurp** [comment]
Thank you for not looking into this issue in 3 years dear Open ID developers ;) We've removed this test so that the test suite can pass. Please close this bug.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
