### ISSUE TITLE
Getting unsigned ax attributes from an openid provider causes a "NoneType object has no attribute get" error

### ISSUE THREAD

**Issue by bcap** [openid/python-openid#60]
When dealing with openid ax atrributes, the consumer.py has a `SuccessResponse.getSignedNS` that returns the signed attributes or `None` is any of the signed attributes are not signed ([link](https://github.com/openid/python-openid/blob/master/openid/consumer/consumer.py#L1785)).

IMO this method should raise an exception or just return the signed ones. Returning `None` means that no attributes were signed at all and also fails when dealing with the result of this method, as instead of an empty array, you get `None`. 

When an OpenID provider redirects to an url with present but unsigned ax attributes, the [`fromSuccessResponse`](https://github.com/openid/python-openid/blob/master/openid/extensions/ax.py#L711) will fail with a "NoneType object has no attribute get" as [this line](https://github.com/openid/python-openid/blob/master/openid/extensions/ax.py#L80) will try to get the current mode on a `None` object

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
