### ISSUE TITLE
When Consumer site sends a redirect, the Auto-Submit stops

### ISSUE THREAD

**Issue by LeoNie312** [openid/python-openid#65]
When I followed the example to submit "http://localhost:8000/id/bob", it didn't auto-submit the html. Instead, the html made by oidutil.autoSubmitHTML, was wrapped around in a "pre" tag and displayed on the page. 

Why did I see this? How can I solve it? Thanks!

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
