### ISSUE TITLE
Yadis Discover iterates through services

### ISSUE THREAD

**Issue by ziima** [openid/python-openid#8]
When OpenID requests are created for provider which has several OpenID versions in its XRDS document, the most prior one is not used but instead they are iterated. I believe problem is at line 109 in yadis/manager.py which returns manager.next() instead manager.current()

I am not sure about consequences in YADIS protocol, maybe it is bug in yadis library as well.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
