### ISSUE TITLE
Will not work over a proxy

### ISSUE THREAD

**Issue by hjwp** [openid/python-openid#83]
Hi there, we've had users complain they can't use openid over our squid proxy.  I think it's because urllib2 doesn't support HTTPS over a proxy... (urllib3 does, if it's of any use).

https://docs.python.org/2/howto/urllib2.html#id15

https://www.pythonanywhere.com/forums/topic/502/#id_post_8109

Not sure if this is a priority for y'all, but thought I'd let you know!

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
