### ISSUE TITLE
Deprecation warning due to invalid escape sequences in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [openid/python-openid#99]
Deprecation warnings are raised due to invalid escape sequences in Python 3.8 . Below is a log of the warnings raised during compiling all the python files. Using raw strings or escaping them will fix this issue.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Wall -m py_compile {}

./openid/extensions/draft/pape2.py:30: DeprecationWarning: invalid escape sequence \d
  TIME_VALIDATOR = re.compile('^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\dZ$')
./openid/extensions/draft/pape5.py:35: DeprecationWarning: invalid escape sequence \d
  TIME_VALIDATOR = re.compile('^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\dZ$')
```

**Comment by hugovk** [comment]
This project is unmaintained: https://github.com/openid/python-openid/issues/62

Use python-openid2 instead:

* https://pypi.org/project/python-openid2
* https://github.com/ziima/python-openid

**Comment by tirkarthi** [comment]
Thanks @hugovk. Closing.
